-- 1. Tabelas de Localização (Geográficas)
CREATE TABLE pais (
    id_pais INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sigla VARCHAR(10) NOT NULL
);

CREATE TABLE estado (
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sigla VARCHAR(2) NOT NULL,
    id_pais INTEGER NOT NULL,
    FOREIGN KEY (id_pais) REFERENCES pais(id_pais)
);

CREATE TABLE cidade (
    id_cidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    id_estado INTEGER NOT NULL,
    FOREIGN KEY (id_estado) REFERENCES estado(id_estado)
);

-- 2. Tabela de Endereço
CREATE TABLE endereco (
    id_endereco INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro VARCHAR(255),
    numero VARCHAR(20),
    bairro VARCHAR(255),
    cep VARCHAR(20),
    complemento VARCHAR(255),
    id_cidade INTEGER NOT NULL,
    FOREIGN KEY (id_cidade) REFERENCES cidade(id_cidade)
);

-- 3. Tabela Cliente (Agora vinculada ao Endereço)
CREATE TABLE cliente (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    data_nascimento DATE,
    id_endereco INTEGER,
    FOREIGN KEY (id_endereco) REFERENCES endereco(id_endereco)
);

-- 4. Tabelas do Negócio (Evento e Ingresso)
CREATE TABLE evento (
    id_evento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data TIMESTAMP NOT NULL,
    capacidade_maxima INTEGER NOT NULL,
    ingressos_restantes INTEGER NOT NULL,
    preco_base DECIMAL(10, 2) NOT NULL
);

CREATE TABLE ingresso (
    id_ingresso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_compra TIMESTAMP NOT NULL,
    valor_pago DECIMAL(10, 2) NOT NULL,
    id_cliente INTEGER NOT NULL,
    id_evento INTEGER NOT NULL,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    FOREIGN KEY (id_evento) REFERENCES evento(id_evento)
);